// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: machine/machine.proto

package machine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Operand  int32  `protobuf:"varint,2,opt,name=operand,proto3" json:"operand,omitempty"`
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Instruction) GetOperand() int32 {
	if x != nil {
		return x.Operand
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output float32 `protobuf:"fixed32,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetOutput() float32 {
	if x != nil {
		return x.Output
	}
	return 0
}

type CompletionParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextDocumentPositionParams *TextDocumentPositionParams `protobuf:"bytes,1,opt,name=text_document_position_params,json=textDocumentPositionParams,proto3" json:"text_document_position_params,omitempty"`
}

func (x *CompletionParams) Reset() {
	*x = CompletionParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionParams) ProtoMessage() {}

func (x *CompletionParams) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionParams.ProtoReflect.Descriptor instead.
func (*CompletionParams) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{2}
}

func (x *CompletionParams) GetTextDocumentPositionParams() *TextDocumentPositionParams {
	if x != nil {
		return x.TextDocumentPositionParams
	}
	return nil
}

type TextDocumentIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URI string `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
}

func (x *TextDocumentIdentifier) Reset() {
	*x = TextDocumentIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextDocumentIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDocumentIdentifier) ProtoMessage() {}

func (x *TextDocumentIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDocumentIdentifier.ProtoReflect.Descriptor instead.
func (*TextDocumentIdentifier) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{3}
}

func (x *TextDocumentIdentifier) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line      int32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Character int32 `protobuf:"varint,2,opt,name=character,proto3" json:"character,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetCharacter() int32 {
	if x != nil {
		return x.Character
	}
	return 0
}

type TextDocumentPositionParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextDocument *TextDocumentIdentifier `protobuf:"bytes,1,opt,name=text_document,json=textDocument,proto3" json:"text_document,omitempty"`
	Position     *Position               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *TextDocumentPositionParams) Reset() {
	*x = TextDocumentPositionParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextDocumentPositionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDocumentPositionParams) ProtoMessage() {}

func (x *TextDocumentPositionParams) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDocumentPositionParams.ProtoReflect.Descriptor instead.
func (*TextDocumentPositionParams) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{5}
}

func (x *TextDocumentPositionParams) GetTextDocument() *TextDocumentIdentifier {
	if x != nil {
		return x.TextDocument
	}
	return nil
}

func (x *TextDocumentPositionParams) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type DidChangeTextDocumentParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextDocument   *VersionedTextDocumentIdentifier  `protobuf:"bytes,1,opt,name=text_document,json=textDocument,proto3" json:"text_document,omitempty"`
	ContentChanges []*TextDocumentContentChangeEvent `protobuf:"bytes,2,rep,name=content_changes,json=contentChanges,proto3" json:"content_changes,omitempty"`
}

func (x *DidChangeTextDocumentParams) Reset() {
	*x = DidChangeTextDocumentParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DidChangeTextDocumentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DidChangeTextDocumentParams) ProtoMessage() {}

func (x *DidChangeTextDocumentParams) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DidChangeTextDocumentParams.ProtoReflect.Descriptor instead.
func (*DidChangeTextDocumentParams) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{6}
}

func (x *DidChangeTextDocumentParams) GetTextDocument() *VersionedTextDocumentIdentifier {
	if x != nil {
		return x.TextDocument
	}
	return nil
}

func (x *DidChangeTextDocumentParams) GetContentChanges() []*TextDocumentContentChangeEvent {
	if x != nil {
		return x.ContentChanges
	}
	return nil
}

type VersionedTextDocumentIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URI     string `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionedTextDocumentIdentifier) Reset() {
	*x = VersionedTextDocumentIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionedTextDocumentIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedTextDocumentIdentifier) ProtoMessage() {}

func (x *VersionedTextDocumentIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedTextDocumentIdentifier.ProtoReflect.Descriptor instead.
func (*VersionedTextDocumentIdentifier) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{7}
}

func (x *VersionedTextDocumentIdentifier) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

func (x *VersionedTextDocumentIdentifier) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TextDocumentContentChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextDocumentContentChangeEvent) Reset() {
	*x = TextDocumentContentChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextDocumentContentChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDocumentContentChangeEvent) ProtoMessage() {}

func (x *TextDocumentContentChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDocumentContentChangeEvent.ProtoReflect.Descriptor instead.
func (*TextDocumentContentChangeEvent) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{8}
}

func (x *TextDocumentContentChangeEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CompletionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label  string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CompletionItem) Reset() {
	*x = CompletionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionItem) ProtoMessage() {}

func (x *CompletionItem) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionItem.ProtoReflect.Descriptor instead.
func (*CompletionItem) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{9}
}

func (x *CompletionItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CompletionItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CompletionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*CompletionItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machine_machine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_machine_machine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_machine_machine_proto_rawDescGZIP(), []int{10}
}

func (x *CompletionResponse) GetItems() []*CompletionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_machine_machine_proto protoreflect.FileDescriptor

var file_machine_machine_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x22, 0x43, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x6e, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x7a, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x66, 0x0a, 0x1d, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x1a, 0x74, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x2a, 0x0a, 0x16, 0x54, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x49, 0x22,
	0x3c, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x91, 0x01,
	0x0a, 0x1a, 0x54, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x44, 0x0a, 0x0d,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xbe, 0x01, 0x0a, 0x1b, 0x44, 0x69, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x4d, 0x0a, 0x0d, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x50, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x22, 0x4d, 0x0a, 0x1f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x49, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x34, 0x0a, 0x1e, 0x54, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3e, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x43, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x41, 0x0a, 0x07,
	0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x32,
	0x9b, 0x01, 0x0a, 0x03, 0x6c, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x09, 0x44, 0x69, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x44,
	0x69, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x4a, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_machine_machine_proto_rawDescOnce sync.Once
	file_machine_machine_proto_rawDescData = file_machine_machine_proto_rawDesc
)

func file_machine_machine_proto_rawDescGZIP() []byte {
	file_machine_machine_proto_rawDescOnce.Do(func() {
		file_machine_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_machine_machine_proto_rawDescData)
	})
	return file_machine_machine_proto_rawDescData
}

var file_machine_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_machine_machine_proto_goTypes = []interface{}{
	(*Instruction)(nil),                     // 0: machine.Instruction
	(*Result)(nil),                          // 1: machine.Result
	(*CompletionParams)(nil),                // 2: machine.CompletionParams
	(*TextDocumentIdentifier)(nil),          // 3: machine.TextDocumentIdentifier
	(*Position)(nil),                        // 4: machine.Position
	(*TextDocumentPositionParams)(nil),      // 5: machine.TextDocumentPositionParams
	(*DidChangeTextDocumentParams)(nil),     // 6: machine.DidChangeTextDocumentParams
	(*VersionedTextDocumentIdentifier)(nil), // 7: machine.VersionedTextDocumentIdentifier
	(*TextDocumentContentChangeEvent)(nil),  // 8: machine.TextDocumentContentChangeEvent
	(*CompletionItem)(nil),                  // 9: machine.CompletionItem
	(*CompletionResponse)(nil),              // 10: machine.CompletionResponse
}
var file_machine_machine_proto_depIdxs = []int32{
	5,  // 0: machine.CompletionParams.text_document_position_params:type_name -> machine.TextDocumentPositionParams
	3,  // 1: machine.TextDocumentPositionParams.text_document:type_name -> machine.TextDocumentIdentifier
	4,  // 2: machine.TextDocumentPositionParams.position:type_name -> machine.Position
	7,  // 3: machine.DidChangeTextDocumentParams.text_document:type_name -> machine.VersionedTextDocumentIdentifier
	8,  // 4: machine.DidChangeTextDocumentParams.content_changes:type_name -> machine.TextDocumentContentChangeEvent
	9,  // 5: machine.CompletionResponse.items:type_name -> machine.CompletionItem
	0,  // 6: machine.Machine.Execute:input_type -> machine.Instruction
	6,  // 7: machine.lsp.DidChange:input_type -> machine.DidChangeTextDocumentParams
	2,  // 8: machine.lsp.Completion:input_type -> machine.CompletionParams
	1,  // 9: machine.Machine.Execute:output_type -> machine.Result
	1,  // 10: machine.lsp.DidChange:output_type -> machine.Result
	10, // 11: machine.lsp.Completion:output_type -> machine.CompletionResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_machine_machine_proto_init() }
func file_machine_machine_proto_init() {
	if File_machine_machine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_machine_machine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instruction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextDocumentIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextDocumentPositionParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DidChangeTextDocumentParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionedTextDocumentIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextDocumentContentChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_machine_machine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machine_machine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_machine_machine_proto_goTypes,
		DependencyIndexes: file_machine_machine_proto_depIdxs,
		MessageInfos:      file_machine_machine_proto_msgTypes,
	}.Build()
	File_machine_machine_proto = out.File
	file_machine_machine_proto_rawDesc = nil
	file_machine_machine_proto_goTypes = nil
	file_machine_machine_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MachineClient is the client API for Machine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (Machine_ExecuteClient, error)
}

type machineClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineClient(cc grpc.ClientConnInterface) MachineClient {
	return &machineClient{cc}
}

func (c *machineClient) Execute(ctx context.Context, opts ...grpc.CallOption) (Machine_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[0], "/machine.Machine/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineExecuteClient{stream}
	return x, nil
}

type Machine_ExecuteClient interface {
	Send(*Instruction) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type machineExecuteClient struct {
	grpc.ClientStream
}

func (x *machineExecuteClient) Send(m *Instruction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *machineExecuteClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MachineServer is the server API for Machine service.
type MachineServer interface {
	Execute(Machine_ExecuteServer) error
}

// UnimplementedMachineServer can be embedded to have forward compatible implementations.
type UnimplementedMachineServer struct {
}

func (*UnimplementedMachineServer) Execute(Machine_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterMachineServer(s *grpc.Server, srv MachineServer) {
	s.RegisterService(&_Machine_serviceDesc, srv)
}

func _Machine_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MachineServer).Execute(&machineExecuteServer{stream})
}

type Machine_ExecuteServer interface {
	Send(*Result) error
	Recv() (*Instruction, error)
	grpc.ServerStream
}

type machineExecuteServer struct {
	grpc.ServerStream
}

func (x *machineExecuteServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *machineExecuteServer) Recv() (*Instruction, error) {
	m := new(Instruction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Machine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.Machine",
	HandlerType: (*MachineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Machine_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "machine/machine.proto",
}

// LspClient is the client API for Lsp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LspClient interface {
	DidChange(ctx context.Context, opts ...grpc.CallOption) (Lsp_DidChangeClient, error)
	Completion(ctx context.Context, opts ...grpc.CallOption) (Lsp_CompletionClient, error)
}

type lspClient struct {
	cc grpc.ClientConnInterface
}

func NewLspClient(cc grpc.ClientConnInterface) LspClient {
	return &lspClient{cc}
}

func (c *lspClient) DidChange(ctx context.Context, opts ...grpc.CallOption) (Lsp_DidChangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lsp_serviceDesc.Streams[0], "/machine.lsp/DidChange", opts...)
	if err != nil {
		return nil, err
	}
	x := &lspDidChangeClient{stream}
	return x, nil
}

type Lsp_DidChangeClient interface {
	Send(*DidChangeTextDocumentParams) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type lspDidChangeClient struct {
	grpc.ClientStream
}

func (x *lspDidChangeClient) Send(m *DidChangeTextDocumentParams) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lspDidChangeClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lspClient) Completion(ctx context.Context, opts ...grpc.CallOption) (Lsp_CompletionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lsp_serviceDesc.Streams[1], "/machine.lsp/Completion", opts...)
	if err != nil {
		return nil, err
	}
	x := &lspCompletionClient{stream}
	return x, nil
}

type Lsp_CompletionClient interface {
	Send(*CompletionParams) error
	Recv() (*CompletionResponse, error)
	grpc.ClientStream
}

type lspCompletionClient struct {
	grpc.ClientStream
}

func (x *lspCompletionClient) Send(m *CompletionParams) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lspCompletionClient) Recv() (*CompletionResponse, error) {
	m := new(CompletionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LspServer is the server API for Lsp service.
type LspServer interface {
	DidChange(Lsp_DidChangeServer) error
	Completion(Lsp_CompletionServer) error
}

// UnimplementedLspServer can be embedded to have forward compatible implementations.
type UnimplementedLspServer struct {
}

func (*UnimplementedLspServer) DidChange(Lsp_DidChangeServer) error {
	return status.Errorf(codes.Unimplemented, "method DidChange not implemented")
}
func (*UnimplementedLspServer) Completion(Lsp_CompletionServer) error {
	return status.Errorf(codes.Unimplemented, "method Completion not implemented")
}

func RegisterLspServer(s *grpc.Server, srv LspServer) {
	s.RegisterService(&_Lsp_serviceDesc, srv)
}

func _Lsp_DidChange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LspServer).DidChange(&lspDidChangeServer{stream})
}

type Lsp_DidChangeServer interface {
	Send(*Result) error
	Recv() (*DidChangeTextDocumentParams, error)
	grpc.ServerStream
}

type lspDidChangeServer struct {
	grpc.ServerStream
}

func (x *lspDidChangeServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lspDidChangeServer) Recv() (*DidChangeTextDocumentParams, error) {
	m := new(DidChangeTextDocumentParams)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Lsp_Completion_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LspServer).Completion(&lspCompletionServer{stream})
}

type Lsp_CompletionServer interface {
	Send(*CompletionResponse) error
	Recv() (*CompletionParams, error)
	grpc.ServerStream
}

type lspCompletionServer struct {
	grpc.ServerStream
}

func (x *lspCompletionServer) Send(m *CompletionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lspCompletionServer) Recv() (*CompletionParams, error) {
	m := new(CompletionParams)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Lsp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.lsp",
	HandlerType: (*LspServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DidChange",
			Handler:       _Lsp_DidChange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Completion",
			Handler:       _Lsp_Completion_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "machine/machine.proto",
}
